### ISSUE TITLE
term for droplet transmission

### ISSUE THREAD

**Issue by PhiBabs935** [infectious-disease-ontology-extensions/ido-covid-19#1]
Do we eventually plan on importing a curated version of TRANS:_droplet spread_ (http://purl.obolibrary.org/obo/TRANS_0000008) to IDO-COVID-19?

**Comment by johnbeve** [comment]
Excellent find! We should definitely import that. I've added it to a list of items to add which I'll be uploading here and to bioportal within the next few days, so I'll go ahead and close this.

**Comment by johnbeve** [comment]
I've imported TRANS:_droplet spread_ and a few other related transmission terms, but I've refined textual definitions, relabeled them, and in some cases reclassified them, e.g. _droplet spread_ is no longer a subclass of _direct_ since it involves transmission by respiratory droplet, and we're treating respiratory droplets as vehicles.

**Comment by PhiBabs935** [comment]
Sounds good to me!
